spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:shop